spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/unifiedauth?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#    password: wsuser
mybatis-plus:
  type-aliases-package: com.auth
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888