server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞时间
        max-wait: 1000ms
        #最大空闲连接，默认8
        max-idle: 200
remoteurl: localhost
remoteport: 8020
filePath: d:/files/
